# Specify the template type. Valid values are as follows.
     # - For Terraform: TF
     # - For AWS CloudFormation: CFT
     # - For Kubernetes: K8S
     template_type: K8S
     # The valid values for terraform_version are 0.11 or 0.12
     ## terraform_version: 0.12